import { Providers } from "./providers"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: '#0F0F0F' }}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
